services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: metar
      POSTGRES_PASSWORD: metar
      POSTGRES_DB: metar_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

volumes:
  db-data: